source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

use_frameworks!

target 'FullAuthIOSClient_Example' do
  pod "FullAuthIOSClient", :path => "../"
  
end

target 'FullAuthIOSClient_Tests' do
  pod "FullAuthIOSClient", :path => "../"

  
end
