# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

osx_image: xcode9.4

branches:
  only:
    - swift4

notifications:
  email:
    - monica.raja@anywhere.co

script:
- set -o pipefail && xcodebuild test -workspace Example/FullAuthIOSClient.xcworkspace -scheme FullAuthIOSClient-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
