# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
  
language: objective-c

osx_image: xcode9.4

cache:
  - cocoapods

branches:
  only:
    - master
    
podfile: Example/Podfile

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

notifications:
  email:
    - monica.raja@anywhere.co
    - ramesh@anywhere.co
    - karthik.samy@anywhere.co
    - sathish.gurunathan@anywhere.co
    - gupta@anywhere.co

script:

#- set -o pipefail && xcodebuild test -destination 'platform=iOS Simulator,name=iPhone 6s' -workspace Example/FullAuthIOSClient.xcworkspace -scheme FullAuthIOSClient-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -workspace Example/FullAuthIOSClient.xcworkspace -scheme FullAuthIOSClient-Example -sdk -destination 'platform=iOS Simulator,name=iPhone 6s' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
