# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
#testing 

language: objective-c

osx_image: xcode9.4

branches:
  only:
    - master
    
podfile: Example/Podfile

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

notifications:
  email:
    - monica.raja@anywhere.co

script:

- set -o pipefail && xcodebuild test -destination 'platform=iOS Simulator,name=iPhone 6s' -workspace Example/FullAuthIOSClient.xcworkspace -scheme FullAuthIOSClient-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
